// Generated by gencpp from file aruco_pose/cupRequest.msg
// DO NOT EDIT!


#ifndef ARUCO_POSE_MESSAGE_CUPREQUEST_H
#define ARUCO_POSE_MESSAGE_CUPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aruco_pose
{
template <class ContainerAllocator>
struct cupRequest_
{
  typedef cupRequest_<ContainerAllocator> Type;

  cupRequest_()
    : OUO(0)  {
    }
  cupRequest_(const ContainerAllocator& _alloc)
    : OUO(0)  {
  (void)_alloc;
    }



   typedef int32_t _OUO_type;
  _OUO_type OUO;





  typedef boost::shared_ptr< ::aruco_pose::cupRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aruco_pose::cupRequest_<ContainerAllocator> const> ConstPtr;

}; // struct cupRequest_

typedef ::aruco_pose::cupRequest_<std::allocator<void> > cupRequest;

typedef boost::shared_ptr< ::aruco_pose::cupRequest > cupRequestPtr;
typedef boost::shared_ptr< ::aruco_pose::cupRequest const> cupRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aruco_pose::cupRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aruco_pose::cupRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aruco_pose::cupRequest_<ContainerAllocator1> & lhs, const ::aruco_pose::cupRequest_<ContainerAllocator2> & rhs)
{
  return lhs.OUO == rhs.OUO;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aruco_pose::cupRequest_<ContainerAllocator1> & lhs, const ::aruco_pose::cupRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aruco_pose

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::aruco_pose::cupRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aruco_pose::cupRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aruco_pose::cupRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aruco_pose::cupRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aruco_pose::cupRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aruco_pose::cupRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aruco_pose::cupRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e03e9f73d1355bf38f3e731f90a1fc9e";
  }

  static const char* value(const ::aruco_pose::cupRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe03e9f73d1355bf3ULL;
  static const uint64_t static_value2 = 0x8f3e731f90a1fc9eULL;
};

template<class ContainerAllocator>
struct DataType< ::aruco_pose::cupRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aruco_pose/cupRequest";
  }

  static const char* value(const ::aruco_pose::cupRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aruco_pose::cupRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 OUO\n"
;
  }

  static const char* value(const ::aruco_pose::cupRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aruco_pose::cupRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.OUO);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cupRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aruco_pose::cupRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aruco_pose::cupRequest_<ContainerAllocator>& v)
  {
    s << indent << "OUO: ";
    Printer<int32_t>::stream(s, indent + "  ", v.OUO);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARUCO_POSE_MESSAGE_CUPREQUEST_H
