// Generated by gencpp from file aruco_pose/nsRequest.msg
// DO NOT EDIT!


#ifndef ARUCO_POSE_MESSAGE_NSREQUEST_H
#define ARUCO_POSE_MESSAGE_NSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aruco_pose
{
template <class ContainerAllocator>
struct nsRequest_
{
  typedef nsRequest_<ContainerAllocator> Type;

  nsRequest_()
    : OAO(0)  {
    }
  nsRequest_(const ContainerAllocator& _alloc)
    : OAO(0)  {
  (void)_alloc;
    }



   typedef int32_t _OAO_type;
  _OAO_type OAO;





  typedef boost::shared_ptr< ::aruco_pose::nsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aruco_pose::nsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct nsRequest_

typedef ::aruco_pose::nsRequest_<std::allocator<void> > nsRequest;

typedef boost::shared_ptr< ::aruco_pose::nsRequest > nsRequestPtr;
typedef boost::shared_ptr< ::aruco_pose::nsRequest const> nsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aruco_pose::nsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aruco_pose::nsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aruco_pose::nsRequest_<ContainerAllocator1> & lhs, const ::aruco_pose::nsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.OAO == rhs.OAO;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aruco_pose::nsRequest_<ContainerAllocator1> & lhs, const ::aruco_pose::nsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aruco_pose

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::aruco_pose::nsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aruco_pose::nsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aruco_pose::nsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aruco_pose::nsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aruco_pose::nsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aruco_pose::nsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aruco_pose::nsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a26ed29ee2d854e1ac3e22595442f5e";
  }

  static const char* value(const ::aruco_pose::nsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a26ed29ee2d854eULL;
  static const uint64_t static_value2 = 0x1ac3e22595442f5eULL;
};

template<class ContainerAllocator>
struct DataType< ::aruco_pose::nsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aruco_pose/nsRequest";
  }

  static const char* value(const ::aruco_pose::nsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aruco_pose::nsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 OAO\n"
;
  }

  static const char* value(const ::aruco_pose::nsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aruco_pose::nsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.OAO);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aruco_pose::nsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aruco_pose::nsRequest_<ContainerAllocator>& v)
  {
    s << indent << "OAO: ";
    Printer<int32_t>::stream(s, indent + "  ", v.OAO);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARUCO_POSE_MESSAGE_NSREQUEST_H
